### ISSUE TITLE
Nullable enums with an empty string fail to get generated

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#118]
In #59, we added support for an empty string as a valid case in a string enum, however, we only tested it on enum schemas _not_ marked as `nullable`.

Turns out, that when marked as `nullable`, OpenAPIKit parses the values slightly [differently](https://github.com/mattpolzin/OpenAPIKit/blob/release/3_0/Sources/OpenAPIKit30/Schema%20Object/JSONSchemaContext.swift#L662-L666), and treats the empty string as a nil string instead. That nil value, when converted to OpenAPIKit's `AnyCodable`, [gets turned](https://github.com/mattpolzin/OpenAPIKit/blob/release/3_0/Sources/OpenAPIKitCore/AnyCodable/AnyCodable.swift#L39) into a `Void`.

Before we introduce a workaround in the generator, @mattpolzin is this intentional behavior, and if so, can you say more about it please?

**Comment by czechboy0** [comment]
To reproduce, we can just use:

```yaml
type: string
nullable: true
enum:
  - foo
  - ""
```

The second enum value will be an empty string when the schema is _not_ nullable, and `Void` when the schema is nullable.

**Comment by mattpolzin** [comment]
Unfortunately this is a known issue with Yams. https://github.com/jpsim/Yams/issues/301

OpenAPIKit has special case decoding of nullable string enums because otherwise a null case gets read in as the string "null" instead of the value `null`, but it is unintentional that the empty string also gets read in as `null`. 

There is a proposed fix for the issue against Yams and a fork with that fix under the CreateAPI project but no indication of whether the fix will be upstreamed.

**Comment by czechboy0** [comment]
Thanks for the find, @mattpolzin - I wonder if @jpsim can tell us more about the prioritization of landing that [fix](https://github.com/jpsim/Yams/pull/351)?

**Comment by czechboy0** [comment]
I suspect we'll need to check for this ourselves in the generator, it's not a big deal, just wanted to try to see if Yams could fix it, but I suspect that'd be a breaking change anyway, so might not be likely.
