### ISSUE TITLE
JSON headers without an explicit content map

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#131]
We support JSON objects in headers, but only when they have an explicit `content` map, as required by the OpenAPI 3.0.3 specification.

However, in practice, some large OpenAPI adopters skip putting JSON headers into `content`, and just put a JSON object schema directly into the `schema` field, which is supposed to only contain string-convertible values.

One example is https://github.com/backstage/backstage/blob/083a4022e573f993c65f596ee77d4f9526136c68/docs/openapi/definitions/auth.yaml#L65

To make it more concrete. To put a JSON object into a header, it should be:

```yaml
Set-Cookie:
  description: Nonce cookie
  content:
    application/json:
      schema:
        $ref: '#/components/schemas/Nonce-Cookie'    
```

But some OpenAPI documents just do:

```yaml
Set-Cookie:
  description: Nonce cookie
  schema:
    $ref: '#/components/schemas/Nonce-Cookie'
```

On the one hand, they're technically not spec compliant. On the other, they are large projects with popular OpenAPI documents, and some other OpenAPI generators already work around this.

One idea: detect this case and basically internally convert the latter to the former. If a JSON object is detected as the schema in a parameter, automatically treat it as JSON. Wouldn't be too much work, but opens the can of worms of the generator implementing not the _OpenAPI specification_, but _how people use the OpenAPI specification_ in the wild.

What do y'all think?

**Comment by simonjbeaumont** [comment]
> On the one hand, they're technically not spec compliant. On the other, they are large projects with popular OpenAPI documents, and some other OpenAPI generators already work around this.

How much precedence is there for the workaround and, OOI, what does OpenAPIKit do when it sees this? 

> One idea: detect this case and basically internally convert the latter to the former. If a JSON object is detected as the schema in a parameter, automatically treat it as JSON.

Where would we do this? Would it be a new initial phase in the generator pipeline? One that massages away known idiomatic violations of the spec, before passing it on to the generator, which remains strict on spec compliance?

> Wouldn't be too much work, but opens the can of worms of the generator implementing not the _OpenAPI specification_, but _how people use the OpenAPI specification_ in the wild.
> 
> What do y'all think?

My first reaction is that we don't go out of our way to handle things that aren't valid OAS. However, if this is a very widespread idiom then we might need to be more lenient.

Do you have any numbers on how widespread this is? E.g. "of the X documents I sampled, Y have this".

**Comment by mattpolzin** [comment]
> what does OpenAPIKit do when it sees this?

OpenAPIKit can't know whether the kind of header shown in the OP is correct for the given API or not, to the best of my knowledge. Headers gain a default `style` of `simple` and a default `explode` of `false` when only a `schema` is specified (no content map). In this style, it is possible to encode/decode primitives, arrays, and even objects. Therefore, you cannot tell at face value whether an OpenAPI document really does mean `simple` encoding or whether it intends a JSON encoding.

**Comment by czechboy0** [comment]
@mattpolzin Check me on this, but my [read](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#style-values) of the allowed `style` values for headers is that only `simple` is allowed, and it doesn't allow `object`, only `primitive` and `array`.

That's why I assumed that when people put an object schema in a header parameter, they actually want JSON. But maybe I'm not interpreting the text correctly, interested what you and @simonjbeaumont get from reading that section of the specification.

**Comment by mattpolzin** [comment]
That section of the specification leaves something to be desired, in my opinion, but here's my read of it.

1. As I mentioned in my last comment, `simple` style and `explode` false are assumed for the `schema` values we are talking about here because they are in the `header` location.
2. The `style` definitions table you linked to is misleading at best for the `type` column only stating `array`, but what I believe they intended to mean is that you should always interpret `simple` values as being arrays (comma separated) for which the degenerate case of only one value is equivalent to just a primitive.
3. The `style` examples table alludes to support of objects by giving examples of objects for the `simple` style.
4. A deeper read of the RFC linked to for the `simple` style talks more about how objects are encoded in this style: for `explode` false, you get alternating key/value array elements, e.g. `"beans": { "hello": "world", "nice": "job"}` -> `beans=hello,world,nice,job`.

**Comment by czechboy0** [comment]
Yeah I could see that if we insert more assumptions, I can also see a reasonable way to represent objects in headers, but... is that how people use it? I don't think I've ever seen (have you?) the simple key/value pairs in headers, but I've seen (in multiple projects) minimized JSON headers. Thus this issue, as I'm trying to somehow balance the read of the specification with how people use it in the wild.

I guess one way would be to look at some OpenAPI documents that do `type: object` in headers without a content map, and see how they interpret the bytes, and I'll also take a look at other code generators in other languages, as this ambiguity makes it difficult to implement this support with confidence.

**Comment by mattpolzin** [comment]
This situation is definitely unfortunate. Particularly because the specification does not yield ambiguous results here: there are valid alternatives and each is representable within the spec; uncertainty is entirely created by misuse of the spec (albeit a very easy place to make mistakes as a document author).

> I don't think I've ever seen (have you?) the simple key/value pairs in headers [...]

I haven't, but I have not seen many examples of complex JSON objects in headers, either (not saying they aren't out there, I just haven't looked for them). Where I work, we use exploded deep object encoding 🤷 for query parameters.

I don't have strong opinions on the handling of this for the `swift-openapi-generator`, but my advice would be to handle heuristics that modify semantics where both the original and modified OpenAPI document technically have valid meaning by offering the user of your project a choice. I figure that at least we can hope a single API is internally consistent about what it means when it uses the "shorthand" described by this issue. Then, someone using `swift-openapi-generator` could turn on one handling or the other depending on the API in question. Alternatively, a simple script (potentially even one vendered by this project) that modified the shorthand into the longhand could be pipelined in front of `swift-openapi-generator` to similarly offer this choice to implementors on a per-API basis.

**Comment by czechboy0** [comment]
I tend to agree, our [project scope documentation](https://swiftpackageindex.com/apple/swift-openapi-generator/0.1.5/documentation/swift-openapi-generator/project-scope-and-goals#Principle-Faithfully-represent-the-OpenAPI-document) specifically calls this out – that adopters should preprocess their OpenAPI document instead of looking for the generator to "fix it up" for them.

Ok, thanks for talking this through with me, @simonjbeaumont and @mattpolzin – I now agree that this isn't something we should build into our generator.

One last thing before I close this issue – I recently collected about 1200 OpenAPI real-world documents and will run a query on it about how widespread this usage is, will update here once I have the results.

**Comment by czechboy0** [comment]
Ok, so only 6 out of 1192 OpenAPI documents in my test set use JSON headers.

One used both a content map, and also a shorthand JSON object, combined with the `style: deepObject`. So we should enhance that support in #18.

The other 5 used just the shorthand JSON object, but in some of them, I suspect they actually mean the header key/value pairs.

So now I'm even more convinced we shouldn't automatically JSON-ify headers, and we should expand to support other parameter and header styles in #18.
