### ISSUE TITLE
Disregarding/Overwriting additionalProperties: false in openapi.yml

### ISSUE THREAD

**Issue by sureshjoshi** [apple/swift-openapi-generator#305]
Hi, this may already be documented somewhere, but I wasn't able to find it/didn't know exactly the terminology to look for.

I see this documentation about `additionalProperties`:
https://swiftpackageindex.com/apple/swift-openapi-generator/0.2.3/documentation/swift-openapi-generator/generating-custom-codable-conformance-methods#Object-structs-with-additional-properties

But I'm dealing with a case where the server generated OpenAPI is -incorrectly- stating that `additionalProperties: false`, and the generated decoders failed in Prod because something new was added to the API (and I'm guessing it was the `decoder.ensureNoAdditionalProperties` which bombed out.

Is there any generator configuration I can use to override and always allow unknown keys?

**Comment by sureshjoshi** [comment]
Note: My current workaround is to grab the OpenAPI yaml, and then find/replace, which appears to be working just fine.

**Comment by czechboy0** [comment]
> My current workaround is to grab the OpenAPI yaml, and then find/replace, which appears to be working just fine.

Yes that's the correct workaround until the server fixes their behavior, either by not sending undocumented keys since they explicitly specify `additionalProperties: false`, or by removing `additionalProperties: false` from the doc.

Since this is just the server not being compliant with its specification, either the behavior or the specification needs to change. We don't provide options to deliberately disregard parts of the source OpenAPI document.

**Comment by sureshjoshi** [comment]
👍🏽 

Cool beans, I'm on board with that!
