### ISSUE TITLE
SOAR-0007 enhancement request/question - more precisely throwing accessors

### ISSUE THREAD

**Issue by porglezomp** [apple/swift-openapi-generator#320]
Sorry to get this in after all the discussion and PR was merged, I had a question about the way the accessors are throwing.
One of the merged test cases has the following:
```swift
case json(Swift.String)
public var json: Swift.String {
   get throws {
       switch self {
       case let .json(body): return body
       }
   }
}
```

Should this be generated as a throwing accessor?
I think as a client of this, I would like if this was just `get` instead of `get throws`, more accurately reflecting the documented API.
The points as I see them:

Non-throwing:
- More accurately represents the underlying documented API
- If the API evolves to have multiple cases, now users can more easily identity places they should update their code to handle potential new sources of errors because they require a `try` now.
- Consistent with the API stability expectations—changes to the OpenAPI document change the interface, things can change if more content types are added

Throwing:
- Slightly simpler / more uniform
- Provides more stability, clients won't break when the API evolves. But see above, maybe they should break?

**Comment by simonjbeaumont** [comment]
@porglezomp thanks for taking some time to think this through.

> Provides more stability, clients won't break when the API evolves. But see above, maybe they should break?

It's a fair question, but I think that the route we took aligns more closely with the existing design patterns.

Specifically, if we were to extend your reasoning further, we shouldn't generate an `enum` at all when there is only one content.

Additionally, it's likely that folks using this feature will also be using it in conjunction with the throwing getter for the response status too (e.g. `.ok`, or `.created`), which will _always_ be throwing (because of the `.undocumented` enum case). So, even if we were to generate non-throwing getters for single content, most users would still need to have `try` for the API request, and for the matching of the response outcome (before body):

```swift
// what we have now
print(try await client.getGreeting().ok.body.json.message)
//                     ^             ^       ^
//                     |             |       `- Throws if body did not conform to documented JSON.
//                     |             |
//                     |             `- Throws if HTTP response is not 200 (OK).
//                     |           
//                     |          
//                     |
//                     `- Throws if there is an error making the API call.

// proposed in this issue
print(try await client.getGreeting().ok.body.json.message)
//                     ^             ^       ^
//                     |             |       `- Non-throwing.
//                     |             |
//                     |             `- Throws if HTTP response is not 200 (OK).
//                     |           
//                     |          
//                     |
//                     `- Throws if there is an error making the API call.
```

The only case where you might benefit from this is where you first unwrap the outcome, which would allow you to not use the `try` later:

```swift
let okResponse = try await client.getGreeting().ok
print(okResponse.body.json.message)  // <-- No try needed
```

Given that, do you still feel as strongly about it?

**Comment by porglezomp** [comment]
The latter design with the two statements is exactly what I was thinking.
I'm currently writing light wrappers to provide slightly more consistency over the generated APIs, and was interested in the opportunity to have my wrapper break when those changes happen.

I agree the single line case is likely to be much more common, and don't feel extremely strongly that this is necessary, it's just the main remaining question I had while reviewing the new generated APIs.

**Comment by czechboy0** [comment]
This feedback was considered in SOAR-0007, closing.
