### ISSUE TITLE
programmatic init

### ISSUE THREAD

**Issue by pkasson** [apple/swift-openapi-generator#497]
### Question

Is it possible to generate client code without building within Xcode (i.e. dynamically) ... and how to start server programmatically ?

**Comment by simonjbeaumont** [comment]
Hey @pkasson!

When you say "dynamically, without building in Xcode", do you mean you'd like to:

1. build outside of Xcode, in which case, yes. Checkout any of our tutorials that mention SwiftPM (cf. Xcode) or any of our examples which can be built `swift build`; or
2. build in Xcode but "dynamically", by which you mean some form of automatic build where you don't have to trigger a build to pick up changes and have the generated code available for you to use in the consuming module. In which case, no, you cannot. The code is generated by a Swift package plugin, which runs at build time. If this is something you'd like, please file a request against Xcode at https://feedbackassistant.apple.com. 


When you say "start the server programmatically", you can use `swift run` on the command line with any of our server examples, or otherwise start the server by running the binary directly. 

Does this answer your questions?

**Comment by pkasson** [comment]
@simonjbeaumont - thanks for the great response !

1.  Yes - build via a script, API using SPM, so that client code can be built outside XC
2. As in #1, using SPM, generate the code, to be able to run later - i.e. a 'batch' build to run / test in a script

Happy holidays ;)

**Comment by simonjbeaumont** [comment]
Ok. Probably start looking at one of the examples in the Examples/ directory of this repo. There are two using manual generation workflows. One uses Swift package command plugin, the other uses a makefile. They are the ones prefixed with manual-generation- and each has a covering readme. 

They should help you get started.

**Comment by czechboy0** [comment]
Hi @pkasson, hopefully the info Si provided can get you started. If you have follow-up questions, please reply here and we can reopen the issue if needed.
