### ISSUE TITLE
Configuring the Xcode plugin to generate the source code for checkin

### ISSUE THREAD

**Issue by avnerbarr** [apple/swift-openapi-generator#516]
### Question

I'm using the Xcode plugin successfully but the code completion is working slowly, the generated names are very cumbersome and navigating the generated code is awkward. I can't find where the generated code is actually located when I "cmd click" to navigate to it. 

<img width="600" alt="image" src="https://github.com/apple/swift-openapi-generator/assets/2404795/48d00fa0-dd72-41c0-8896-5707b985e02b">

My thought is to continue using the Xcode plugin to produce the code in a file (as the cli tool does), and then I will add the generated code to my project and check it in. This will also allow me to customize some of the awkwardness.

Here are some examples of the cumbersome code I am encountering

<img width="512" alt="image" src="https://github.com/apple/swift-openapi-generator/assets/2404795/fe847662-fc39-45f9-bb92-41e06f47acb7">

```
client.post_sol_api_sol_v3_sol_order_sol_oco(<#T##input: Operations.post_sol_api_sol_v3_sol_order_sol_oco.Input##Operations.post_sol_api_sol_v3_sol_order_sol_oco.Input#>)
```

**Comment by czechboy0** [comment]
Hi @avnerbarr,

the long names are due to your OpenAPI doc not specifying a human-friendly `operationId` for each operation. You could ask the vendor of the OpenAPI doc to add those, and then you'll get _exactly_ those names as long as they stick to the recommended character set for `operationId`, which is `[a-zA-Z0-9_]`.

Regarding issues using Xcode with build plugins, please direct those to https://feedbackassistant.apple.com, those are not tracked as part of this project.

But yes, manually invoking the CLI is another supported way to use the tool: https://swiftpackageindex.com/apple/swift-openapi-generator/1.2.0/documentation/swift-openapi-generator/manually-invoking-the-generator-cli

If you have any specific questions or issues related to this project, please file new GitHub issues, thanks!
