### ISSUE TITLE
Generated method names based on description rather than the API path

### ISSUE THREAD

**Issue by avnerbarr** [apple/swift-openapi-generator#517]
### Question

Seems that the name of the method is by API path. Would be nice if it could be by the description of the method instead.

Example (based on Binance spec)

Description of method is:

`Compressed/Aggregate Trades List`

and the API spec is:

`GET /api/v3/aggTrades`

The generated method I get is:

`get_sol_api_sol_v3_sol_aggTrades`

Would like it to be similar to the description instead, i.e.:

`get_compressed_aggregate_trade_list`

Here is the generated code:
```
/// Compressed/Aggregate Trades List
    ///
    /// Get compressed, aggregate trades. Trades that fill at the time, from the same order, with the same price will have the quantity aggregated.
    /// - If `fromId`, `startTime`, and `endTime` are not sent, the most recent aggregate trades will be returned.
    /// - Note that if a trade has the following values, this was a duplicate aggregate trade and marked as invalid:
    ///
    ///   p = '0' // price
    ///
    ///   q = '0' // qty
    ///
    ///   f = -1 // ﬁrst_trade_id
    ///
    ///   l = -1 // last_trade_id
    ///
    /// Weight(IP): 2
    ///
    /// - Remark: HTTP `GET /api/v3/aggTrades`.
    /// - Remark: Generated from `#/paths//api/v3/aggTrades/get`.
    internal func get_sol_api_sol_v3_sol_aggTrades(_ input: Operations.get_sol_api_sol_v3_sol_aggTrades.Input) async throws -> Operations.get_sol_api_sol_v3_sol_aggTrades.Output {
```

**Comment by czechboy0** [comment]
Hi @avnerbarr,

as mentioned in #516, the issue here is that the OpenAPI document didn't specify the `operationId` field for each operation. Either ask the vendor to provide it, or edit the OpenAPI document yourself and add that field to each operation, at which point you'll see exactly those names in the generated code, as long as you keep to the character set recommended by the OpenAPI specification in: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#fixed-fields-8

A safe character set to use for operationId is `[a-zA-Z0-9_]`.

**Comment by avnerbarr** [comment]
Thanks for the explanation!

I see that the `/` characters in the API path are replaced with `sol` , for example here:

```
/// - Remark: HTTP `GET /api/v3/ticker/price`.
    /// - Remark: Generated from `#/paths//api/v3/ticker/price/get`.
```
`get_sol_api_sol_v3_sol_ticker_sol_price`


What does `sol` stand for? Is there a simple way (the spec is a few thousand lines long) to remove that? Is is prolific all over.

Thanks!

**Comment by czechboy0** [comment]
The `sol` is the replacement word for the `/` character, since a slash isn't a legal character in a Swift identifier. Details here: https://swiftpackageindex.com/apple/swift-openapi-generator/1.2.0/documentation/swift-openapi-generator/soar-0001

You could use some custom automation that preprocesses your OpenAPI document, but you might also consider opening a PR to the upstream OpenAPI document and adding well thought-out `operationId` for each operation, that way everyone can benefit.

In either case, Swift OpenAPI Generator is a tool that generates Swift code from an OpenAPI document, so processing of OpenAPI documents themselves is out of scope of this tool.

You might also check out the filtering feature, if you're only using a small subset of the OpenAPI document in your project: https://swiftpackageindex.com/apple/swift-openapi-generator/1.2.0/documentation/swift-openapi-generator/configuring-the-generator#Document-filtering

**Comment by avnerbarr** [comment]
Yes I am filtering. I have a new question now :) will open a separate topic
