### ISSUE TITLE
ClientError/ServerError's underlyingErrorDescription only produces meaningful output for LocalizedErrors

### ISSUE THREAD

**Issue by francescomikulis** [apple/swift-openapi-generator#631]
### Motivation

A client of the OpenAPIGenerator was reporting an error, which in the logs appeared as a very unhelpful:
`(MyClassTypeScope.(unknown context at $107abc012).MyErrorType error 0.)`
It seems the this issue is caused by the fact that `ServerError.underlyingErrorDescription` is not falling back to `String(describing: underlyingError)`, but using another representation that is not very useful in practice.

### Proposed solution

Please consider moving the error description mechanism that surfaces the content of the underlying error to use `String(describing: underlyingError)` instead of the current mechanism.

### Alternatives considered

Forcing all clients to conform to `LocalizedError` in order to get good logging for an error is error-prone.

**Comment by czechboy0** [comment]
Hi @francescomikulis,

yeah this is currently somewhat intentional, to prevent leaking potentially sensitive data unintentionally through logs.

That said, I am open to discussing this more and potentially reconsider.

@fabianfett, can you chime in here with your experience in this area from the Postgres client, and @FranzBusch as well maybe? cc @simonjbeaumont

**Comment by simonjbeaumont** [comment]
Should we have different behaviour for debug and production servers? ISTR this is how some of the web frameworks behave with regard to providing the error in the response payload.

**Comment by czechboy0** [comment]
Right, some do, I suspect this issue is about making the behavior consistent between transports. There is the extra consideration of the wrapping of the thrown error in a ServerError, and how those descriptions interact.

**Comment by czechboy0** [comment]
In Swift OpenAPI Generator, we explicitly conformed all the errors we want printed nicely to LocalizedError: https://developer.apple.com/documentation/foundation/localizederror

The description of `LocalizedError` says:

> A specialized error that provides localized messages describing the error and why it occurred.

At the moment, I'd consider the current behavior desirable. But I'm willing to be convinced otherwise with more info/examples/precedent/docs.

**Comment by czechboy0** [comment]
Closing for now - the solution is for user-defined errors to conform to `LocalizedError`.
