### ISSUE TITLE
Generate a convenience method to create a response case without any parameters

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#651]
### Motivation

Today, some responses have no headers nor body (for example, 204 No Content).

In generated code it looks like this:

```swift
internal enum Output: Sendable, Hashable {
    internal struct NoContent: Sendable, Hashable {
        /// Creates a new `NoContent`.
        internal init() {}
    }
    case noContent(Operations.addPollAnswer.Output.NoContent)
}
```

And when writing a server handler, adopters have to spell it as:

```
return .noContent(.init())
```

The `(.init())` bit is unnecessary, and we should make this common case prettier.

### Proposed solution

One possible way to fix this (I welcome other ideas, though) is by generating a `static var` for any response cases that have _no required_ values in the initializer. In practice, since response bodies are always required, this would only apply to responses with _no body_ and with _only optional response headers_.

The generated code would look closer to the following:

```swift
internal enum Output: Sendable, Hashable {
    internal struct NoContent: Sendable, Hashable {
        /// Creates a new `NoContent`.
        internal init() {}
    }
    case noContent(Operations.addPollAnswer.Output.NoContent)
    internal static var noContent: Self { .noContent(.init()) } // <<< this is new
}
```

which would allow the server handler to just have:

```swift
return .noContent
```

**Comment by simonjbeaumont** [comment]
Hunch: Agree that this is a nice QOL improvement for this one case.

Thought: we initially tried to have the generator work without too much "look-ahead", i.e. that it wouldn't need to reach into other parts to work out whether it could or couldn't provide a nicety. We've now got a few places where we do that, but each of these will increase the runtime of the generation. I wonder how common this is, because if we have to pay the price of working out that we _can't_ do it for almost every operation, it may not be worth it?

Question: should we consider (instead, or as well as) having the headers parameter `Operations.addPollAnswer.Output.NoContent.init` be defaulted to `.init()` if there are no required headers.

**Comment by czechboy0** [comment]
Discussed offline: let's do this only when there are no headers or body, but do not do it if there are only non-required headers.

**Comment by czechboy0** [comment]
Okay @arthurcro, feel free to pick this up

**Comment by arthurcro** [comment]
Hey @czechboy0! I made some progress on the implementation and I have a draft version working. However, before I open a pull request, I'd like to discuss some specific details with you to ensure I've correctly interpreted the requirements.

Adding the static property to this function won't work because it needs to be generated outside the struct declaration.

https://github.com/apple/swift-openapi-generator/blob/58a276ac955bd50e3d252a9e79ebabdfe0d54b03/Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponse.swift#L25

Instead, I was thinking we could add it to: https://github.com/apple/swift-openapi-generator/blob/58a276ac955bd50e3d252a9e79ebabdfe0d54b03/Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponseOutcome.swift#L31 instead.

It would mean updating the signature to something like:

```swift
func translateResponseOutcomeInTypes(
    _ outcome: OpenAPI.Operation.ResponseOutcome,
    operation: OperationDescription,
    operationJSONPath: String
) throws -> (
  payloadStruct: Declaration?,
  enumCase: Declaration,
  staticProperty: Declaration?,
  throwingGetter: Declaration
) { ... }
```

What do you think? :slightly_smiling_face:

Then, I realised we also need to check for `responseKind.wantsStatusCode` before adding this static property because if that's the case, it adds an extra associated value to the generated enum case which we can't default in the expression assigned to the static property.

Please let me know if you have any concerns!

**Comment by czechboy0** [comment]
Agreed with all of the above, and let's only generate the convenience static property for cases that don't require the explicit status code as an associated value.
